[package]
name = "kolyan-model"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
jsonschema = { version = "0.30", default-features = false }
kolyan-types = { path = "../kolyan-types" }
futures-core.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"
